// <auto-generated />
namespace VexTeamNetwork.NetworkMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_addTeams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_addTeams));
        
        string IMigrationMetadata.Id
        {
            get { return "201504252145366_initial_addTeams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
