// <auto-generated />
namespace VexTeamNetwork.AccountMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateUserId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUserId2));
        
        string IMigrationMetadata.Id
        {
            get { return "201504252108065_updateUserId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
